In [1]:
import deepsparse

In [2]:
import os
os.environ["WAND_OPT_FLAGS"] = "default,~pyramids"

In [3]:
pipeline = deepsparse.Pipeline.create(
    task="text-generation", 
    model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
    use_deepsparse_cache=False,
    prompt_processing_sequence_length=4,
    max_generated_tokens=64,
    sequence_length=128
)

2023-08-19 21:47:03 deepsparse.transformers WARNING  The neuralmagic fork of transformers may not be installed. It can be installed via `pip install nm_transformers`


Using pad_token, but it is not set yet.
2023-08-19 21:48:07 deepsparse.transformers.pipelines.text_generation INFO     Compiling an auxiliary engine to process a prompt with a larger processing length. This improves performance, but may result in additional memory consumption.
2023-08-19 21:48:08 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.6.0.20230815 COMMUNITY | (134dba40) (release) (optimized) (system=avx2, binary=avx2)
2023-08-19 21:48:35 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx


In [9]:
pipeline2 = deepsparse.Pipeline.create(
    task="text-generation", 
    model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
    use_deepsparse_cache=True,
    prompt_processing_sequence_length=4,
    max_generated_tokens=64,
    sequence_length=128
)

Using pad_token, but it is not set yet.
2023-08-19 21:50:10 deepsparse.transformers.pipelines.text_generation INFO     Compiling an auxiliary engine to process a prompt with a larger processing length. This improves performance, but may result in additional memory consumption.
2023-08-19 21:50:12 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
2023-08-19 21:50:37 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx


In [11]:
output = pipeline(sequences="fib(n):")
print(output.sequences[0])

print("\n\n\n\n")

output = pipeline2(sequences="fib(n):")
print(output.sequences[0])


    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

print(fib(int(input())))






    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

print(fib(int(input())))


In [16]:
sequence = "Finish the following function for computing a fibonacci sequence: \n\n fib(n):"
print(pipeline(sequences=[sequence]).sequences[0])
print("\n\n\n")
print(pipeline2(sequences=[sequence]).sequences[0])



    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code






    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code


### Deconstructing the Pipeline

In [17]:
engine = pipeline.engine
multitoken_engine = pipeline.multitoken_engine

In [18]:
input_tokens = pipeline.tokenizer(
    sequence,
    return_tensors="np",
    max_length=pipeline.sequence_length,
    padding="max_length",
    truncation=True,
)

In [19]:
input_ids = input_tokens["input_ids"]
print(input_ids)

[[50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256 50256
  50256 50256 48658   262  1708  2163   329 14492   257 12900   261 44456
   8379    25   220   628 12900     7    77  2599]]


In [20]:
attention_mask = input_tokens["attention_mask"]
print(attention_mask)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [21]:
positions = attention_mask.cumsum(1) * attention_mask
print(positions)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10
  11 12 13 14 15 16 17 18]]


In [24]:
from deepsparse.transformers.utils.helpers import create_causal_mask
causal_mask = create_causal_mask(input_ids, attention_mask)
print(causal_mask[:,:,-20:,-20:])

[[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
   [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]]]


In [25]:
onnx_input_names = multitoken_engine.onnx_input_names_no_cache
assert(name in input_tokens for name in onnx_input_names)
print(onnx_input_names)

['input_ids', 'attention_mask', 'positions', 'causal_mask']


In [26]:
input_tokens = dict(
    **input_tokens, positions=positions, causal_mask=causal_mask
)

In [27]:
engine_input = [input_tokens[name] for name in onnx_input_names]

In [30]:
pipeline._reset_engines_cache()

In [31]:
import numpy 
def engine_inputs_for_prefill(tokens):
    num_batches = len(tokens) // pipeline.prompt_processing_sequence_length

    token_batches = [tokens[i * pipeline.prompt_processing_sequence_length : (i + 1) * pipeline.prompt_processing_sequence_length] for i in range(0, num_batches)]
    
    for idx, token_batch in enumerate(token_batches):
        engine_inputs = []
        num_cached_entries = multitoken_engine.num_non_blank_cache_entries
        # print(num_cached_entries)
        
        for name in multitoken_engine.onnx_input_names_no_cache:
            if name == "input_ids":
                assert len(engine_inputs) == 0
                engine_input = numpy.array([token_batch])
                
            elif name == "attention_mask":
                assert len(engine_inputs) == 1
                # create an empty attention mask
                engine_input = numpy.zeros(
                    (1, pipeline.sequence_length), dtype=numpy.int64
                )
                # fill it out with 1s (from the right), so that the number
                # of unmasked entries is equal to the sum of:
                engine_input[
                    :,
                    -(
                        # ...the number of current input tokens...
                        pipeline.prompt_processing_sequence_length
                        # ...and the number of the previous cache entries
                        + num_cached_entries
                    ) :,
                ] = 1
                
            elif name == "causal_mask":
                continue
                
            elif name == "positions":
                if pipeline.prompt_processing_sequence_length == 1:
                    # we need to treat `positions` as if we were in
                    # the autoregressive mode
                    engine_input = numpy.array([[idx]], dtype=numpy.int64)
                else:
                    engine_input = (
                        numpy.arange(
                            num_cached_entries,
                            num_cached_entries
                            + pipeline.prompt_processing_sequence_length,
                        )
                        .reshape(1, -1)
                        .astype(numpy.int64)
                    )

            # print(f"{name}:")
            # print(engine_input)
            # print(engine_input.shape)
            
            engine_inputs.append(engine_input)

        assert "causal_mask" in multitoken_engine.onnx_input_names_no_cache
        causal_mask = create_causal_mask(input_ids=engine_inputs[0], attention_mask=engine_inputs[1])
        engine_inputs.append(causal_mask)

        # print("causal_mask:")
        # print(causal_mask)
        # print(causal_mask.shape)

        yield engine_inputs

In [32]:
INDEX = 32
cache_onnx_names = [
    name
    for name in multitoken_engine.engine.input_names
    if name.startswith("past_key_values")
]

In [33]:
def decode(tokens):
    input_ids = numpy.array([[tokens[-1]]])
    
    attention_mask = numpy.zeros((1, engine.sequence_length), dtype=numpy.int64)
    num_tokens_processed = min(len(tokens), engine.sequence_length)  # cap by seq len
    attention_mask[:, -num_tokens_processed:] = 1    

    causal_mask = create_causal_mask(input_ids, attention_mask)
    positions = numpy.array([[len(tokens) - 1]], dtype=numpy.int64)
    
    engine_inputs_map = dict(
        input_ids=input_ids,
        attention_mask=attention_mask,
        causal_mask=causal_mask,
        positions=positions
    )

    engine_inputs = [
        engine_inputs_map[name] for name in engine.onnx_input_names_no_cache
    ]

    return call(engine, engine_inputs)

In [34]:
def prefill(tokens):
    prompt_logits = []
    
    # loop over multitoken engine
    for engine_inputs in engine_inputs_for_prefill(tokens):
        logits = call(multitoken_engine, engine_inputs)
        prompt_logits.append(logits)
    
    # expand kv cache for new size 124 --> 127
    engine.kv_cache._state = kv_cache_insert(engine.kv_cache._state, num_items=multitoken_engine.input_ids_length - engine.input_ids_length)

    # loop of singletoken engine for the rest
    tokens_processed = engine.kv_cache.total_num_processed_tokens
    while tokens_processed < len(tokens):
        logits = decode(tokens[:tokens_processed + 1])
        prompt_logits.append(logits)
        tokens_processed += 1
    
    return prompt_logits

In [35]:
def sample_token(logits):
    return numpy.argmax(logits)

In [36]:
def kv_cache_slice(kv_cache, slice_idx):
    for key in kv_cache:
        kv_cache[key] = numpy.ascontiguousarray(kv_cache[key][:,:,slice_idx:,:])
    return kv_cache

def kv_cache_insert(kv_cache, num_items = 1, padding_value = 0):
    indices = [0] * num_items
    for key, value in kv_cache.items():
        dtype = value.dtype
        padding_value = numpy.array(padding_value, dtype=dtype)
        kv_cache[key] = numpy.insert(value, indices, padding_value, axis=2)

    return kv_cache

def call(eng, inputs):
    inp = eng.add_kv_cache_to_input(inputs)
    
    logits, *kvs = eng.engine.run(inp, True)
    new_kv_cache_state = {name: arr for name, arr in zip(cache_onnx_names, kvs)}

    eng.kv_cache.total_num_processed_tokens += eng.input_ids_length
    eng.kv_cache._state = kv_cache_slice(new_kv_cache_state, eng.input_ids_length)

    return logits

In [37]:
engine.sequence_length

128

In [184]:
tokens = engine_input[0][engine_input[1].nonzero()].tolist()
pipeline._reset_engines_cache()

print(tokens)
logits = prefill(tokens)
tokens.append(sample_token(logits[-1][0,-1,:])) # assume always batch = 1, last token of last logit in array

# first token from prefill was generated
while len(tokens) < engine.sequence_length:
    print(tokens)
    logits = decode(tokens)
    tokens.append(sample_token(logits[0,-1,:])) # assume always batch = 1, last token of last logit in array

# print(engine.kv_cache._state["past_key_values.0.key"][0,0,-INDEX:,0])
# print(engine.kv_cache._state["past_key_values.0.value"][0,0,-INDEX:,0])
# print(engine.kv_cache._state["past_key_values.19.key"][0,0,-INDEX:,0])
# print(engine.kv_cache._state["past_key_values.19.value"][0,0,-INDEX:,0])

[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198, 50284]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198, 50284, 361]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198, 50284, 361, 299]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198, 50284, 361, 299, 6624]
[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, 198, 50284, 361, 299, 6624, 657]
[48658, 262, 1708, 2163, 329, 14492, 257

In [42]:
print(pipeline.tokenizer.decode(tokens))

Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Examples for


In [43]:
pipeline._reset_engines_cache()

onnx_input_names = (
    pipeline.multitoken_engine.onnx_input_names_no_cache
    if pipeline.multitoken_engine
    else pipeline.engine.onnx_input_names_no_cache
)
engine_input = pipeline.tokens_to_engine_input(input_tokens, onnx_input_names)
tokens_theirs, logits_theirs = pipeline.prompt_inference(engine_input)

while len(tokens_theirs) < pipeline.sequence_length:
    token, logits = pipeline.autoregressive_inference(tokens_theirs)
    tokens_theirs.append(token)
    
print(engine.kv_cache._state["past_key_values.0.key"][0,0,-INDEX:,0])
print(engine.kv_cache._state["past_key_values.0.value"][0,0,-INDEX:,0])
print(engine.kv_cache._state["past_key_values.19.key"][0,0,-INDEX:,0])
print(engine.kv_cache._state["past_key_values.19.value"][0,0,-INDEX:,0])

[-2.16584    -1.4835675  -0.82798475  2.728714    2.230249    0.136684
 -2.4744277  -3.7903032  -0.44804883  1.8597361   3.2892575   1.1238453
 -0.535056   -2.4058022  -2.6181865   0.82309175  3.7468169   0.9127281
 -0.08818069 -3.5193567  -2.554974    0.42606103  2.8396277   3.6084752
  0.720097   -3.140173   -2.3983316  -1.1198903   1.4021769   2.4038355
  1.416564   -1.1770982 ]
[-0.11449916  0.47542867  0.03680322 -0.4064121   0.34018266  0.11729242
 -0.29119202  1.6026565  -0.60162723  1.6026565   0.03134436  0.005808
  0.03680322  0.34018266  1.0944448   0.89051616  1.9490317  -0.8315846
  0.8142212  -0.22642836  0.36906892  1.9490317  -0.15412031  1.0944448
  0.89051616  1.9490317   0.03680322  0.03680322  0.55909103  0.03680322
  0.76835376  0.07582108]
[-1.4705226   2.3718867   1.5622201   0.20804703 -0.930273   -5.223105
 -2.31877     3.5253658   3.8794327   3.3048825  -2.4029026  -2.4765668
 -0.68623084  1.3053839   6.9972997   4.6631894  -0.957654   -4.965276
 -5.222634    

In [44]:
print(pipeline.tokenizer.decode(tokens_theirs))

Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Examples for


In [350]:
engine.kv_cache._state["past_key_values.0.key"].shape

(1, 16, 127, 64)

In [321]:
arr = numpy.ones((2,4,124,16), dtype=numpy.uint8)
print(arr.shape)

(2, 4, 124, 16)


In [334]:
indices = [0] * 3
updated = numpy.insert(arr, indices, 0, axis=2)

In [335]:
print(arr.data.contiguous)
print(updated.data.contiguous)

True
True


In [302]:
print(engine.kv_cache)
print(multitoken_engine.kv_cache)

In [305]:
print(engine.sequence_length)
print(engine.input_ids_length)

print(multitoken_engine.sequence_length)
print(multitoken_engine.input_ids_length)

print(engine.kv_cache.capacity)
print(multitoken_engine.kv_cache.capacity)

128
1
128
4
124
124


In [297]:
engine.transfer_cache_state(cache=multitoken_engine.kv_cache)

In [300]:
print(multitoken_engine.kv_cache.capacity)

127


In [299]:
print(engine.kv_cache.capacity)

127


In [128]:
pipeline._reset_engines_cache()

for engine_inputs in engine_inputs_for_prefill(tokens):
    multitoken_engine(engine_inputs)
    print("\n\n")

0
input_ids:
[[16594   257  2163   284]]
(1, 4)
attention_mask:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]]
(1, 128)
positions:
[[0 1 2 3]]
(1, 4)
causal_mask:
[[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0


In [272]:
from typing import Optional, List, Dict
from deepsparse import Context
from deepsparse.pipeline import DEEPSPARSE_ENGINE, create_engine
from deepsparse.transformers.utils.helpers import overwrite_onnx_model_inputs
from transformers import AutoTokenizer

class DecoderEngine:
    def __init__ (
        self,
        onnx_file_path: str, 
        sequence_length: int = 1024,
        input_ids_length: int = 1,
        engine_context: Optional[Context] = None,
    ):

        onnx_file_path, _, data_type = overwrite_onnx_model_inputs(
            onnx_file_path=onnx_file_path,
            batch_size=1,
            sequence_length=sequence_length,
            input_ids_length=input_ids_length,
        )

        self.past_key_value_dtype = data_type
        self.engine = create_engine(
            onnx_file_path=onnx_file_path,
            engine_type=DEEPSPARSE_ENGINE,
            engine_args={},
            context=engine_context,
        )
        print(self.engine)

        self.onnx_inputs = self.engine.input_names
        
        self.past_onnx_inputs = [
            name for name in self.engine.input_names
            if name.startswith("past_key_values")
        ]

        self.non_past_onnx_inputs = [
            name for name in self.engine.input_names
            if not name.startswith("past_key_values")
        ]
    
    def __call__(
        self,
        inputs: Dict[str, numpy.ndarray],
        past_key_values: Dict[str, numpy.ndarray],
        val_inp: bool = True
    ):
        # format input
        inp = [past_key_values[name] if name.startswith("past_key_values") 
               else inputs[name] for name in self.engine.input_names]

        # run inference
        logits, *kvs = self.engine.run(inp, True)
        past_key_values = {name: arr for name, arr in zip(self.past_onnx_inputs, kvs)}
        
        return logits, past_key_values


class Model:
    def __init__(
        self,
        onnx_file_path: str,
        sequence_length: int = 1024,
        multi_token_length: int = 16,
        engine_context: Optional[Context] = None,
        singletoken_engine = None,
        multitoken_engine = None,
    ):
        self.sequence_length = sequence_length
        self.multi_token_length = multi_token_length

        if singletoken_engine is not None and multitoken_engine is not None:
            self.singletoken_engine = singletoken_engine
            self.multitoken_engine = multitoken_engine
        else:
            self.singletoken_engine = DecoderEngine(
                onnx_file_path=onnx_file_path,
                engine_context=engine_context,
                sequence_length=sequence_length,
                input_ids_length=1,
            )
    
            self.multitoken_engine = DecoderEngine(
                onnx_file_path=onnx_file_path,
                engine_context=engine_context,
                sequence_length=sequence_length,
                input_ids_length=self.multi_token_length,
            )

        assert self.multitoken_engine.past_key_value_dtype == self.singletoken_engine.past_key_value_dtype
        self.past_key_value_dtype = self.multitoken_engine.past_key_value_dtype
        
        assert len(self.singletoken_engine.non_past_onnx_inputs) == 4
        assert "input_ids" in self.singletoken_engine.non_past_onnx_inputs
        assert "attention_mask" in self.singletoken_engine.non_past_onnx_inputs
        assert "causal_mask" in self.singletoken_engine.non_past_onnx_inputs
        assert "positions" in self.singletoken_engine.non_past_onnx_inputs

    # create empty kv caches with the proper sizes based on onnx graph
    def init_past_key_values(self):
        past_key_values = {}
        for idx, name in enumerate(self.multitoken_engine.onnx_inputs):
            if name.startswith("past_key_values"):
                shape = self.multitoken_engine.engine.input_shapes[idx]
                past_key_values[name] = numpy.zeros(shape, dtype=self.past_key_value_dtype)

        return past_key_values

    # insert into every K,V matrix in the list
    # BAD [SLOW] --- A copy of arr with values inserted. Note that insert does not occur in-place: a new array is returned. If axis is None, out is a flattened array.
    def insert_past_key_values(self, past_key_values, num_items=1, padding_value=0):
        for name in past_key_values:
            padding_value = numpy.array(padding_value, dtype=self.past_key_value_dtype)
            past_key_values[name] = numpy.insert(past_key_values[name], [0]*num_items, padding_value, axis=2)
        return past_key_values

    # slice every K,V matrix in the list
    # BAD [SLOW] --- calls .ascontinugousarray
    def slice_past_key_values(self, past_key_values, slice_idx):
        for name in past_key_values:
            past_key_values[name] = numpy.ascontiguousarray(past_key_values[name][:,:,slice_idx:,:])
        return past_key_values
    
    # slice input tokens into groups, make inputs dict
    def engine_inputs_for_prefill(self, tokens):
        num_batches = len(tokens) // self.multi_token_length
        token_batches = [tokens[i * self.multi_token_length : (i+1) * self.multi_token_length] for i in range(0, num_batches)]

        num_processed_tokens = 0
        for idx, token_batch in enumerate(token_batches):
            engine_inputs = {}
            engine_inputs["input_ids"] = numpy.array([token_batch])

            # make attention mask from the right
            engine_inputs["attention_mask"] = numpy.zeros((1, self.sequence_length), dtype=numpy.int64)
            engine_inputs["attention_mask"][:, -(self.multi_token_length + num_processed_tokens):] = 1
            
            # make positions (building from the right)
            assert self.multi_token_length > 1
            engine_inputs["positions"] = numpy.arange(
                num_processed_tokens, num_processed_tokens + self.multi_token_length
            ).reshape(1, -1).astype(numpy.int64)

            # make causal mask (building from the right)
            engine_inputs["causal_mask"] = create_causal_mask(
                input_ids=engine_inputs["input_ids"], 
                attention_mask=engine_inputs["attention_mask"]
            )


            yield engine_inputs

    def engine_inputs_for_decode(self, tokens):
        assert(len(tokens) < self.sequence_length)
        
        engine_inputs = {}
        engine_inputs["input_ids"] = numpy.array([[tokens[-1]]])
        engine_inputs["attention_mask"] = numpy.zeros((1, self.sequence_length), dtype=numpy.int64)
        engine_inputs["attention_mask"][:, -len(tokens):] = 1
        
        engine_inputs["causal_mask"] = create_causal_mask(
            engine_inputs["input_ids"], 
            engine_inputs["attention_mask"]
        )
        engine_inputs["positions"] = numpy.array([[len(tokens) - 1]], dtype=numpy.int64)
        
        return engine_inputs
    
    # run prefill inference
    def prefill(self, tokens):
        assert len(tokens) < self.sequence_length - 1
        
        # initialize state
        past_key_values = self.init_past_key_values()
        tokens_processed = 0
        
        # loop over multitoken engine
        for inputs in self.engine_inputs_for_prefill(tokens):        
            logits, past_key_values = self.multitoken_engine(inputs, past_key_values)
            tokens_processed += self.multi_token_length
            
            # (this is BAD - calls np.ascontiguous) - cleanup past_kv state 
            past_key_values = self.slice_past_key_values(past_key_values, self.multi_token_length)
            
        # (this is BAD - returns a copy) - expand kv cache for single token engine 
        past_key_values = self.insert_past_key_values(past_key_values, num_items=(self.multi_token_length-1))

        # loop of singletoken engine for anything left over
        while tokens_processed < len(tokens):
            logits, past_key_values = self.decode(
                tokens=tokens[:tokens_processed+1],
                past_key_values=past_key_values
            )
            tokens_processed += 1

        assert logits.shape[0] == 1 # assert batch 1 right now
        return logits[:,:,:], past_key_values
    
    # run decode inference
    def decode(self, tokens, past_key_values):    
        engine_inputs = self.engine_inputs_for_decode(tokens)

        logits, past_key_values = self.singletoken_engine(
            inputs=engine_inputs,
            past_key_values=past_key_values
        )

        # cleanup state (this is BAD - calls np.ascontiguous)
        past_key_values = self.slice_past_key_values(past_key_values, 1)

        assert logits.shape[0] == 1 # assert batch 1 right now
        assert logits.shape[1] == 1 # assert only one element
        return logits[:,:,:], past_key_values

def sample_token(logits):
    assert(logits.shape[0] == 1)
    return numpy.argmax(logits[0,-1,:])

model = Model(
    onnx_file_path=onnx_path,
    sequence_length=128,
    multi_token_length=16,
    singletoken_engine=model.singletoken_engine,
    multitoken_engine=model.multitoken_engine
)

tokenizer = AutoTokenizer.from_pretrained(model_path)
tokenizer.padding_side = "left"
if not tokenizer.pad_token:
    tokenizer.pad_token = tokenizer.eos_token

def generate(model, tokenizer, text):
    input_tokens = tokenizer(text, return_tensors="np", max_length=model.sequence_length, padding="longest", truncation=False,)
    tokens = input_tokens["input_ids"][input_tokens["attention_mask"].nonzero()].tolist()

    # prefill
    logits, past_key_values = model.prefill(tokens)
    tokens.append(sample_token(logits))

    # run decode
    while len(tokens) < model.sequence_length and tokens[-1] != tokenizer.eos_token_id:
        logits, past_key_values = model.decode(tokens, past_key_values)
        tokens.append(sample_token(logits))
            
    return tokens
    
tokens = generate(model, tokenizer, sequence)
print(tokenizer.decode(tokens))

Using pad_token, but it is not set yet.


Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>


In [263]:
print(type(tokenizer.eos_token_id))

<class 'int'>


In [266]:
print(tokens)

[48658, 262, 1708, 2163, 329, 14492, 257, 12900, 261, 44456, 8379, 25, 220, 628, 12900, 7, 77, 2599, 198, array([0, 0, 0, ..., 0, 0, 0])]


In [220]:
logits.shape

(1, 51200)

In [205]:
onnx_path =  "/home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx"
model_path = "/home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/deployment"

model = Model(
    onnx_file_path=onnx_path,
    sequence_length=128,
    multi_token_length=16
)

2023-08-20 01:52:24 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx


deepsparse.engine.Engine:
	onnx_file_path: /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
	batch_size: 1
	num_cores: 8
	num_streams: 1
	scheduler: Scheduler.default
	fraction_of_supported_ops: 1.0
	cpu_avx_type: avx2
	cpu_vnni: False


2023-08-20 01:52:54 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx


deepsparse.engine.Engine:
	onnx_file_path: /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
	batch_size: 1
	num_cores: 8
	num_streams: 1
	scheduler: Scheduler.default
	fraction_of_supported_ops: 1.0
	cpu_avx_type: avx2
	cpu_vnni: False


Using pad_token, but it is not set yet.


In [197]:
len(tokens)

18

In [206]:
model.prefill(tokens)

RuntimeError: NM: error: Got invalid dimensions for input: causal_mask for the following indices
 index: 2 Got: 128 Expected: 1
 Please fix either the inputs or the model.

{'input_ids': array([[[48658,   262,  1708,  2163,   329, 14492,   257, 12900,   261,
         44456,  8379,    25,   220,   628, 12900,     7,    77,  2599]]]), 'attention_mask': array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]), 'causal_mask': array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 1, 0, 0],
         [0, 0, 0, ..., 1, 1, 0],
         [0, 0, 0, ..., 1, 1, 1]]]]), 'positions': array([[0]])}


RuntimeError: NM: error: Invalid rank for input: input_ids Got: 3 Expected: 2 Please fix either the inputs or the model.

# Intenally Managed

In [62]:
import deepsparse
from deepsparse.transformers.utils.helpers import create_causal_mask

In [2]:
pipeline = deepsparse.Pipeline.create(
    task="text-generation", 
    model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
    use_deepsparse_cache=True,
    prompt_processing_sequence_length=4,
    max_generated_tokens=64,
    sequence_length=128
)

2023-08-20 11:07:42 deepsparse.transformers WARNING  The neuralmagic fork of transformers may not be installed. It can be installed via `pip install nm_transformers`
Using pad_token, but it is not set yet.
2023-08-20 11:07:54 deepsparse.transformers.pipelines.text_generation INFO     Compiling an auxiliary engine to process a prompt with a larger processing length. This improves performance, but may result in additional memory consumption.
2023-08-20 11:07:56 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.6.0.20230815 COMMUNITY | (134dba40) (release) (optimized) (system=avx2, binary=avx2)
2023-08-20 11:08:20 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.c

In [5]:
sequence = "Finish the following function for computing a fibonacci sequence: \n\n fib(n):"

In [6]:
pipeline(sequences=sequence)

TextGenerationOutput(sequences=['\n\n    if n == 0:\n        return 0\n    elif n == 1:\n        return 1\n    else:\n        return fib(n-1) + fib(n-2)\n\n# Call the function.\nprint(fib(5))\n\n# This code'], logits=None, session_id=None)

In [9]:
singletoken_engine = pipeline.engine
multitoken_engine = pipeline.multitoken_engine
assert singletoken_engine.kv_cache == multitoken_engine.kv_cache
kv_cache = singletoken_engine.kv_cache

In [25]:
engine_inputs = pipeline.process_inputs(pipeline.parse_inputs(sequences=sequence))[0]

In [271]:
import numpy

multitoken_length = pipeline.prompt_processing_sequence_length
sequence_length = pipeline.sequence_length

def empty_past_key_values(engine):
    past_key_values = {}
    for idx, name in enumerate(engine.engine.input_names):
        if name.startswith("past_key_values"):
            shape = engine.engine.input_shapes[idx]
            past_key_values[name] = numpy.zeros(shape, dtype=engine.kv_cache_data_type)

    return past_key_values

def engine_inputs_for_decode(tokens):
    assert(len(tokens) < sequence_length)
    
    engine_inputs = {}
    engine_inputs["input_ids"] = numpy.array([[tokens[-1]]])
    engine_inputs["attention_mask"] = numpy.zeros((1, sequence_length), dtype=numpy.int64)
    engine_inputs["attention_mask"][:, -len(tokens):] = 1
    
    engine_inputs["causal_mask"] = create_causal_mask(
        engine_inputs["input_ids"],
        engine_inputs["attention_mask"]
    )
    engine_inputs["positions"] = numpy.array([[len(tokens) - 1]], dtype=numpy.int64)
    
    return engine_inputs

def engine_inputs_for_prefill(tokens):
    num_batches = len(tokens) // multitoken_length
    token_batches = [tokens[i * multitoken_length : (i+1) * multitoken_length] for i in range(0, num_batches)]

    for idx, token_batch in enumerate(token_batches):
        num_processed_tokens = multitoken_length * idx
        
        engine_inputs = {}
        engine_inputs["input_ids"] = numpy.array([token_batch])

        # make attention mask from the right
        engine_inputs["attention_mask"] = numpy.zeros((1, sequence_length), dtype=numpy.int64)
        engine_inputs["attention_mask"][:, -(num_processed_tokens + multitoken_length):] = 1

        # make positions (building from the right)
        assert multitoken_length > 1
        engine_inputs["positions"] = numpy.arange(
            num_processed_tokens, num_processed_tokens + multitoken_length
        ).reshape(1, -1).astype(numpy.int64)

        # make causal mask (building from the right)
        engine_inputs["causal_mask"] = create_causal_mask(
            input_ids=engine_inputs["input_ids"], 
            attention_mask=engine_inputs["attention_mask"]
        )

        yield engine_inputs

def call_engine(engine, engine_inputs, past_key_values):
    # format inputs as list
    inputs = [
        past_key_values[name] if name.startswith("past_key_values") 
        else engine_inputs[name] for name in engine.engine.input_names
    ]

    # run inference
    logits, *kvs = engine.engine._eng_net.execute_list_out(inputs, engine.kv_cache._kv_cache)

    # format output as dict
    past_names = [name for name in engine.engine.input_names if name.startswith("past_key_values")]
    past_key_values = {name: arr for name, arr in zip(past_names, kvs)}
    
    return logits, past_key_values

# bad -- returns a numpy.insert returns a full copy (update does NOT happen in place)
def insert_past_key_values(past_key_values, num_items=1, padding_value=0):
    dtype = next(iter(past_key_values.values())).dtype

    for name in past_key_values:
        padding_value = numpy.array(padding_value, dtype=dtype)
        past_key_values[name] = numpy.insert(past_key_values[name], [0]*num_items, padding_value, axis=2)
    return past_key_values

# bad --- calls np.ascontiguous
def slice_past_key_values(past_key_values, slice_idx):
    for name in past_key_values:
        past_key_values[name] = numpy.ascontiguousarray(past_key_values[name][:,:,slice_idx:,:])
    return past_key_values
    
# maintians the kv cache state at pipeline level
def decode_maintain(tokens, past_key_values):    
    engine_inputs = engine_inputs_for_decode(tokens)

    logits, past_key_values = call_engine(
        singletoken_engine,
        engine_inputs=engine_inputs,
        past_key_values=past_key_values
    )

    # cleanup state (this is BAD - calls np.ascontiguous)
    past_key_values = slice_past_key_values(past_key_values, 1)

    assert logits.shape[0] == 1 # assert batch 1 right now
    assert logits.shape[1] == 1 # assert only one element
    return logits, past_key_values

# maintians the kv cache state at pipeline level
def prefill_maintain(tokens):
    tokens_processed = 0
    past_key_values = empty_past_key_values(multitoken_engine)

    for engine_inputs in engine_inputs_for_prefill(tokens):
        logits, past_key_values = call_engine(
            multitoken_engine, 
            engine_inputs=engine_inputs, 
            past_key_values=past_key_values
        )
        tokens_processed += multitoken_length

        # BAD - calls np.ascontgious - cleans up that engine returns past with prior_seq_len + input_ids_len
        past_key_values = slice_past_key_values(past_key_values, multitoken_length)
            
    # (this is BAD - returns a copy) - expand kv cache for single token engine 
    past_key_values = insert_past_key_values(past_key_values, num_items=(multitoken_length-1))

    # loop of singletoken engine for anything left over
    while tokens_processed < len(tokens):
        logits, past_key_values = decode_maintain(
            tokens=tokens[:tokens_processed+1],
            past_key_values=past_key_values
        )
        tokens_processed += 1
    
    return logits, past_key_values

empty_past_key_values_multi = empty_past_key_values(multitoken_engine)
empty_past_key_values_single = empty_past_key_values(singletoken_engine)

# does not maintian kv cache state at pipeline level
def decode(tokens):
    engine_inputs = engine_inputs_for_decode(tokens)

    logits, past_key_values = call_engine(
        singletoken_engine,
        engine_inputs=engine_inputs,
        past_key_values=empty_past_key_values_single
    )

    return logits

# does not maintain the state at pipeline level
def prefill(tokens):
    tokens_processed = 0
    
    for engine_inputs in engine_inputs_for_prefill(tokens):
        logits, _ = call_engine(
            multitoken_engine, 
            engine_inputs=engine_inputs, 
            past_key_values=empty_past_key_values_multi
        )
        tokens_processed += multitoken_length

    # loop of singletoken engine for anything left over
    while tokens_processed < len(tokens):
        logits = decode(tokens[:tokens_processed+1])
        tokens_processed += 1
        
    return logits

def sample_token(logits):
    assert(logits.shape[0] == 1)
    return numpy.argmax(logits[0,-1,:])

eos_token = pipeline.tokenizer.eos_token_id

print("without maintaining")
pipeline._reset_engines_cache()
engine_inputs = pipeline.process_inputs(pipeline.parse_inputs(sequences=sequence))[0]
tokens = engine_inputs[0][engine_inputs[1].nonzero()].tolist()

logits = prefill(tokens)
tokens.append(sample_token(logits))
while len(tokens) < sequence_length and tokens[-1] != eos_token:
    logits = decode(tokens)
    tokens.append(sample_token(logits))

print(pipeline.tokenizer.decode(tokens))

print("\n\nmaintaining")
pipeline._reset_engines_cache()
engine_inputs = pipeline.process_inputs(pipeline.parse_inputs(sequences=sequence))[0]
tokens = engine_inputs[0][engine_inputs[1].nonzero()].tolist()

logits, past_key_values = prefill_maintain(tokens)
tokens.append(sample_token(logits))
while len(tokens) < sequence_length and tokens[-1] != eos_token:
    logits, past_key_values = decode_maintain(tokens, past_key_values)
    tokens.append(sample_token(logits))
    
print(pipeline.tokenizer.decode(tokens))

without maintaining
Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>


maintaining
Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>


In [278]:
def prefill_pipeline(pipeline, tokens):
    num_tokens_processed = 0
    for engine_inputs in pipeline.engine_inputs_for_prefill(tokens):
        _, logits = pipeline.multitoken_engine(engine_inputs)
        num_tokens_processed += multitoken_length

    if num_tokens_processed > 0:
        pipeline.engine.transfer_cache_state(cache=pipeline.multitoken_engine.kv_cache)

    run_tokens = [] if num_tokens_processed == 0 else tokens[:num_tokens_processed]
    for token in tokens[num_tokens_processed:]:
        run_tokens.append(token)
        new_token, logits = pipeline.autoregressive_inference(run_tokens)
    return logits
    
pipeline._reset_engines_cache()
engine_inputs = pipeline.process_inputs(pipeline.parse_inputs(sequences=sequence))[0]
tokens = engine_inputs[0][engine_inputs[1].nonzero()].tolist()

logits = prefill_pipeline(pipeline, tokens)
tokens.append(sample_token(logits))

while len(tokens) < pipeline.sequence_length and tokens[-1] != eos_token:
    _, logits = pipeline.autoregressive_inference(tokens)
    tokens.append(sample_token(logits))

print(pipeline.tokenizer.decode(tokens))

Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code is contributed by Nikhil Kumar Singh(nickzuck_007)
<|endoftext|>


In [277]:
print(f"{sequence}{pipeline(sequences=sequence).sequences[0]}")

Finish the following function for computing a fibonacci sequence: 

 fib(n):

    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

# Call the function.
print(fib(5))

# This code


In [279]:
pipeline2 = deepsparse.Pipeline.create(
    task="text-generation", 
    model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
    use_deepsparse_cache=False,
    prompt_processing_sequence_length=4,
    max_generated_tokens=64,
    sequence_length=128
)

Using pad_token, but it is not set yet.
2023-08-20 13:44:57 deepsparse.transformers.pipelines.text_generation INFO     Compiling an auxiliary engine to process a prompt with a larger processing length. This improves performance, but may result in additional memory consumption.
2023-08-20 13:44:58 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
2023-08-20 13:45:23 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the transformer model at /home/robertgshaw/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/model.onnx/model.onnx
